In [13]:
pip install torch torchvision opencv-python open3d timm matplotlib pillow

Note: you may need to restart the kernel to use updated packages.


In [14]:
import cv2
import torch
import numpy as np
import open3d as o3d
from PIL import Image
from torchvision.transforms import Compose, Resize, ToTensor, Normalize
import matplotlib.pyplot as plt

In [19]:
img_path = "tomandjerry.jpeg"
img_bgr = cv2.imread(img_path)
img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
img_pil = Image.fromarray(img_rgb)

# Convert PIL to NumPy array
img_np = np.array(img_pil)

# Load MiDaS
midas = torch.hub.load("intel-isl/MiDaS", "DPT_Hybrid", trust_repo=True)
midas.eval()
midas_transforms = torch.hub.load("intel-isl/MiDaS", "transforms").dpt_transform

# Transform and predict
input_batch = midas_transforms(img_np)
with torch.no_grad():
    prediction = midas(input_batch)
    depth = prediction.squeeze().cpu().numpy()

# Combine with original RGB
depth_resized = cv2.resize(depth, (img_rgb.shape[1], img_rgb.shape[0]))
encoded_matrix = np.dstack((img_rgb, depth_resized))  # (H, W, 4)

Using cache found in /Users/rexouyang/.cache/torch/hub/intel-isl_MiDaS_master
Using cache found in /Users/rexouyang/.cache/torch/hub/intel-isl_MiDaS_master


In [20]:
print(encoded_matrix)

[[[ 125.       183.       197.       444.9362 ]
  [ 126.       184.       198.       441.46848]
  [ 127.       183.       198.       441.10468]
  ...
  [  97.       175.       213.       920.7736 ]
  [  97.       175.       213.       871.28687]
  [  84.       162.       200.       724.78827]]

 [[ 125.       183.       197.       438.27927]
  [ 125.       183.       197.       443.49152]
  [ 126.       182.       197.       445.95197]
  ...
  [  97.       175.       213.       925.1483 ]
  [  97.       175.       213.       909.4141 ]
  [  84.       162.       200.       877.2552 ]]

 [[ 124.       182.       196.       446.52936]
  [ 124.       182.       196.       449.49225]
  [ 126.       182.       197.       450.96213]
  ...
  [  97.       175.       213.       932.0784 ]
  [  97.       175.       213.       927.3466 ]
  [  84.       162.       200.       923.58887]]

 ...

 [[ 179.       130.       160.      1614.242  ]
  [ 178.       129.       159.      1616.4381 ]
  [ 176.  